version: '3'
services:

  app:
    container_name: node_api_monitor
    image: asabhi6776/node-api-monitor:1.8
    entrypoint: ["bash", "-c", "node index.js"]
    restart: always
    volumes:
      - ./.env:/code/.env:rw